name: Unit Tests Workflow

on:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
    name: Unit Tests [Node v${{ matrix.node }}]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          #cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Run unit tests
        timeout-minutes: 8
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        run: pnpm run test:coverage

      - name: Report coverage
        if: always()
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          coverage-file: ./coverage/report.json
          base-coverage-file: ./coverage/report.json
